name: Executar Código Python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar ambiente Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Instalar dependências
      run: pip install py_adyen_encrypt

    - name: Executar script Python
      run: python encry.py  # Substitua 'seu_script.py' pelo nome do seu arquivo Python

